// Code generated by "stringer -type=Cryptocurrency"; DO NOT EDIT.

package currency

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EUR-1]
	_ = x[USD-2]
	_ = x[USDT-3]
	_ = x[USDC-4]
	_ = x[BTC-5]
	_ = x[ETH-6]
	_ = x[LTC-7]
	_ = x[DOGE-8]
}

const _Cryptocurrency_name = "EURUSDUSDTUSDCBTCETHLTCDOGE"

var _Cryptocurrency_index = [...]uint8{0, 3, 6, 10, 14, 17, 20, 23, 27}

func (i Cryptocurrency) String() string {
	i -= 1
	if i < 0 || i >= Cryptocurrency(len(_Cryptocurrency_index)-1) {
		return "Cryptocurrency(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Cryptocurrency_name[_Cryptocurrency_index[i]:_Cryptocurrency_index[i+1]]
}
